<?php
// Language default 'de'
$lang = strtolower($_POST['lang'] ?? $_GET['lang'] ?? 'de');
if (!in_array($lang, ['de','en'])) $lang = 'de';

// Translations
$T = [
    'de' => [
        'link_not_found' => "❌ Link nicht gefunden oder bereits benutzt.",
        'file_missing' => "❌ Datei nicht mehr vorhanden.",
        'password_required' => "🔐 Passwort erforderlich",
        'enter_password' => "Passwort eingeben",
        'start_download' => "📥 Download starten",
        'no_file_selected' => "❌ Keine Datei ausgewählt.",
        'upload_error' => "❌ Fehler beim Hochladen der Datei.",
        'upload_text' => "⬆️ Hochladen",
        'upload_success' => "✅ Hochladen erfolgreich",
        'creating_zip' => "⏳ ZIP wird erstellt...",
        'temp_dir_error' => "❌ Konnte temporäres Verzeichnis nicht anlegen.",
        'error_upload_file' => "❌ Fehler beim Hochladen der Datei ",
        'wrong_password' => "❌ Falsches Passwort",
        'your_link' => "Dein Link:",
        'copy' => "📋 Kopieren",
        'copied' => "✅ Kopiert!",
        'share_files' => "📤 Dateien teilen",
        'drag_files' => "📂 Dateien hierher ziehen oder klicken",
        'password_optional' => "🔐 Passwort (optional)",
        'download_once' => "⏳ Nur 1× herunterladbar",
        'valid_1h' => "🕐 1 Stunde gültig",
        'valid_3h' => "🕒 3 Stunden gültig",
        'valid_6h' => "🕕 6 Stunden gültig",
        'valid_12h' => "🕛 12 Stunden gültig",
        'valid_1d' => "📅 1 Tag gültig",
        'valid_3d' => "📅 3 Tage gültig",
        'valid_7d' => "📅 7 Tage gültig",
        'valid_14d' => "📅 14 Tage gültig",
        'valid_30d' => "📅 30 Tage gültig",
        'upload_button' => "📤 Hochladen & Link erstellen",
        'selected_files' => "Ausgewählte Datei",
        'selected_files_plural' => "Ausgewählte Dateien",
        'language' => "Sprache",
        'title' => "Dropzone File Sharing",
        'version' => "V.1.4",
        'footer_text' => "© 2025 von Kevin Tobler - <a href='https://kevintobler.ch' target='_blank'>www.kevintobler.ch</a>",
    ],
    'en' => [
        'link_not_found' => "❌ Link not found or already used.",
        'file_missing' => "❌ File no longer available.",
        'password_required' => "🔐 Password required",
        'enter_password' => "Enter password",
        'start_download' => "📥 Start download",
        'no_file_selected' => "❌ No file selected.",
        'upload_error' => "❌ Error uploading the file.",
        'upload_text' => "⬆️ Upload",
        'upload_success' => "✅ Upload finished",
        'creating_zip' => "⏳ Creating ZIP...",
        'temp_dir_error' => "❌ Could not create temporary directory.",
        'error_upload_file' => "❌ Error uploading file ",
        'wrong_password' => "❌ Incorrect password",
        'your_link' => "Your link:",
        'copy' => "📋 Copy",
        'copied' => "✅ Copied!",
        'share_files' => "📤 Share files",
        'drag_files' => "📂 Drag files here or click",
        'password_optional' => "🔐 Password (optional)",
        'download_once' => "⏳ Downloadable only 1x",
        'valid_1h' => "🕐 Valid for 1 hour",
        'valid_3h' => "🕒 Valid for 3 hours",
        'valid_6h' => "🕕 Valid for 6 hours",
        'valid_12h' => "🕛 Valid for 12 hours",
        'valid_1d' => "📅 Valid for 1 day",
        'valid_3d' => "📅 Valid for 3 days",
        'valid_7d' => "📅 Valid for 7 days",
        'valid_14d' => "📅 Valid for 14 days",
        'valid_30d' => "📅 Valid for 30 days",
        'upload_button' => "📤 Upload & create link",
        'selected_files' => "Selected file",
        'selected_files_plural' => "Selected files",
        'language' => "Language",
        'title' => "Dropzone File Sharing",
        'version' => "V.1.4",
        'footer_text' => "© 2025 by Kevin Tobler - <a href='https://kevintobler.ch' target='_blank'>www.kevintobler.ch</a>",
    ]
];

// Use translations
$t = $T[$lang];

